### ISSUE TITLE
有办法直接生成一个选定中文英文2:1的混合字体吗

### ISSUE THREAD

**Issue by TomoeMami** [Asvel/monoback#2]
方便在一些难以设置fallback字体的场景应用

**Comment by Asvel** [comment]
混合两个字体的复杂性远高于调整一个字体的字符宽度，自动化地来做很容易出问题。

如果需要整合型字体，建议找一个现有的整合型字体的生成脚本做基础人工来调，两个字体都确定的情况下需要的面对的问题会少很多。
